
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.valheim.appName }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.valheim.appName }}
spec:
  ports:
    - name: gamePort
      port: {{ .Values.valheim.gamePort }}
      protocol: TCP
      targetPort: {{ .Values.valheim.gamePort }}
    - name: queryPort
      port: {{ .Values.valheim.queryPort }}
      protocol: TCP
      targetPort: {{ .Values.valheim.queryPort }}
  selector:
    app: {{ .Values.valheim.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
