# Default values for valheim-chart
namespace: valheim-chart

valheim:
  appName: valheim-server
  image: "lloesche/valheim-server:latest"
  queryPort: 2457
  gamePort: 2456
  replicaCount: 3
  revisionHistoryLimit: 3
  worldName: weHaulAllDeesNuts
  serverName: 
  serverPassword: 12345
  serverPublic: true
  updateIfIdle: true
  discordWebhook: "https://discord.com/api/webhooks/8171522530..."
  filterSearch: "Got character ZDOID from"
  filterSearchContains: '{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'