apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.api.appName }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.environmentDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.api.appName }}-service
                port:
                  number: {{ .Values.api.webPort }}
            path: /
            pathType: Prefix